kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "knawd-deployer-role"
subjects:
  - kind: ServiceAccount
    name: "knawd-deployer-sa"
roleRef:
  kind: Role
  name: "knawd-deployer-role"
  apiGroup: rbac.authorization.k8s.io
