# permissions for end users to view deployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deployer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: knawd-operator
    app.kubernetes.io/part-of: knawd-operator
    app.kubernetes.io/managed-by: kustomize
  name: deployer-viewer-role
rules:
- apiGroups:
  - cache.knawd.dev
  resources:
  - deployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.knawd.dev
  resources:
  - deployers/status
  verbs:
  - get
