kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "knawd-deployer-role"
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["knawd-deployer-scc"]
    verbs: ["use"]